language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
env:
  - DB=sqlite DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.zip
  - DB=postgres DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.6.x.zip
  - DB=sqlite DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.7.x.zip
  - DB=postgres DJANGO_PACKAGE=https://github.com/django/django/archive/stable/1.7.x.zip
  - DB=sqlite DJANGO_PACKAGE=https://github.com/django/django/archive/master.zip
  - DB=postgres DJANGO_PACKAGE=https://github.com/django/django/archive/master.zip
install: 'pip install $DJANGO_PACKAGE --use-mirrors && pip install .'
script: make test SETTINGS=tests.travis_settings
before_script:
  - psql -c 'create database test_ool;' -U postgres
  - pip install psycopg2
